# Generated by Django 5.0.7 on 2024-08-22 11:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, unique=True)),
                ('bank_icon', models.FileField(blank=True, null=True, upload_to='bank_icons')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('currency_country', models.CharField(max_length=100, unique=True)),
                ('currency_icon', models.FileField(blank=True, null=True, unique=True, upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(editable=False, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number format.', regex='^\\+?1?\\d{9,15}$')])),
                ('users_data_limit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='UserCurrency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wallet_id', models.CharField(max_length=255)),
                ('currency_type', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='FiatWallet',
            fields=[
                ('fiat_wallet_id', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('fiat_wallet_type', models.CharField(max_length=50)),
                ('fiat_wallet_currency', models.CharField(max_length=10)),
                ('fiat_wallet_address', models.CharField(editable=False, max_length=66, unique=True)),
                ('fiat_wallet_balance', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('fiat_wallet_created_time', models.DateTimeField(auto_now_add=True)),
                ('fiat_wallet_updated_time', models.DateTimeField(auto_now=True)),
                ('fiat_wallet_phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number format.', regex='^\\+?1?\\d{9,15}$')])),
                ('fiat_wallet_username', models.CharField(max_length=50, unique=True)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='currency_converter.user')),
            ],
        ),
    ]
