# Generated by Django 5.0.7 on 2024-08-22 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_converter', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatwallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency_converter.user'),
        ),
    ]
