# Generated by Django 5.0.7 on 2024-08-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_converter', '0002_user_fiatwallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=10, unique=True)),
                ('currency_country', models.CharField(max_length=100, unique=True)),
                ('currency_icon', models.FileField(blank=True, null=True, unique=True, upload_to='photos')),
            ],
        ),
    ]
