# Generated by Django 5.0.7 on 2024-08-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_converter', '0004_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_icon',
            field=models.FileField(blank=True, null=True, upload_to='bank_icons'),
        ),
    ]
