# Generated by Django 5.0.7 on 2024-09-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fiat_Currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCurrency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wallet_id', models.CharField(max_length=255)),
                ('currency_type', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
            ],
            options={
                'db_table': 'user_currencies',
                'managed': False,
            },
        ),
    ]
