# Generated by Django 5.0.7 on 2024-09-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fiat_Currency', '0002_usercurrency'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(blank=True, max_length=100, null=True)),
                ('currency_type', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'admincms',
                'managed': False,
            },
        ),
    ]
